### ISSUE TITLE
OP

### ISSUE THREAD

**Issue by dhurley94** [bhardy0630/D-Pong#4]
Who won?

**Comment by bhardy0630** [comment]
Hello,

The issue has been resolved, but I do want you to be advised that resolution of this particular issue has been fraught with problems, with but one fortunate occurance - We have been able to reproduce the "lazy ass" preconditions causing the problem.

Alright enough of that shit - I won, haaaaa (and I got my pizza too!) :)

Leave issue unresolved - still need to finish this bad boy.

**Comment by dhurley94** [comment]
Thank you for resolving the issue promptly!
